kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: svcacct-user-pv-manage
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: svcacct-user-pv-manage
roleRef:
  kind: ClusterRole
  name: svcacct-user-pv-manage
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: devsa01
  namespace: dev-sandbox01