kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-svcacct-users-pv-manage
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-svcacct-users-pv-manage
roleRef:
  kind: ClusterRole
  name: ns-svcacct-users-pv-manage
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system.serviceaccounts:dev-sandbox01
  apiGroup: rbac.authorization.k8s.io