apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  # Replace name below with appropriate label for the policy
  name: devsa01-ns-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: devsa01
  namespace: dev-sandbox01
