apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  # Replace name below with appropriate label for the policy
  name: developers-ns-viewonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  # Replace name below with appropriate LDAP group
  name: Developers