apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard-ingress
spec:
  rules:
  - host: kuard.corp.local 
    http:
      paths:
      - path:
        backend:
          serviceName: kuard
          servicePort: 80
